version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: wallet_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: wallet_keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
    volumes:
      - ./keycloak/wallet-realm.json:/opt/keycloak/data/import/wallet-realm.json
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # Collector HTTP (Jaeger format)
      - "14250:14250"  # gRPC (Jaeger format)
      - "6831:6831/udp"  # Agent UDP
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"    # OTLP/gRPC
      - "4318:4318"    # OTLP/HTTP
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:4317"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      jaeger:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  wallet:
    container_name: wallet_service
    depends_on:
      - postgres
      - jaeger
      - prometheus
      - otel-collector
    build:
      context: ../wallet-service
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
      - OTEL_SERVICE_NAME=wallet-service
    ports:
      - "8081:8081"
      - "9464:9464"

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: wallet_network