spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://postgres:5432/wallet_db
    user: postgres
    password: postgres

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/wallet_db
    username: postgres
    password: postgres

  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/wallet-realm

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO
    org.flywaydb.core: INFO
    org.springframework.data.r2dbc.core.DefaultDatabaseClient: INFO
    io.r2dbc.postgresql.QUERY: INFO
  pattern:
    level: "%5p [${traceId:-}]"
  trace:
    log-headers: false

server:
  port: 8081

management:
  otlp:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
  server:
    port: 9464